version: '3'

services:
  container1:
    image: nextjs-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - test-vol:/app/.next/server/pages/
  # container2:
  #   image: nextjs-image
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - test-vol:/app/.next/server/pages/

volumes:
  test-vol:
    
