version: '3'

services:
  container1:
    image: nextjs-image-production
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3000:80
    volumes:
      - test-vol:/app/.next/server/pages/
  container2:
    image: nextjs-image-production
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3001:80
    volumes:
      - test-vol:/app/.next/server/pages/

volumes:
  test-vol:
    
